// ─── FULL IPL PLAYER DATABASE (150+ players, 2008-2024) ───────────────────────
const P = (name, nat, teams, role, bat, bowl, debut, era, titles, caps, flags) => ({
  name, nat, teams, role, bat, bowl, debut, era, titles,
  orangeCap: caps[0], purpleCap: caps[1],
  captain: flags[0], finisher: flags[1], keeper: flags[2],
  allrounder: flags[3], aggressive: flags[4], overseas: nat !== "Indian",
  spin: bowl.includes("spin") || bowl.includes("off-break") || bowl.includes("leg-break") || bowl.includes("slow"),
  pace: bowl.includes("fast") || bowl.includes("medium"),
  leftBat: bat.includes("Left"),
  legend: flags[5] || false, iconic: flags[6] || false,
  active: era.includes("present") || debut >= 2018,
  earlyEra: debut <= 2011,
});

const IPL_PLAYERS = [
// ── INDIA ──────────────────────────────────────────────────────────────────────
P("MS Dhoni","Indian",["CSK","RPS"],"Wicketkeeper-Batsman","Right","Medium",2008,"2008-present",5,[false,false],[true,true,true,false,false,true,true]),
P("Virat Kohli","Indian",["RCB"],"Batsman","Right","Medium",2008,"2008-present",0,[true,false],[true,false,false,false,false,true,true]),
P("Rohit Sharma","Indian",["DC","MI"],"Batsman","Right","Off-break",2008,"2008-present",5,[false,false],[true,false,false,false,true,true,true]),
P("Suresh Raina","Indian",["CSK","GL"],"All-rounder","Left","Off-break",2008,"2008-2021",3,[false,false],[false,true,false,true,false,true,false]),
P("Harbhajan Singh","Indian",["MI","CSK","KKR"],"Bowler","Right","Off-break spin",2008,"2008-2021",2,[false,false],[false,false,false,false,false,true,false]),
P("Yuvraj Singh","Indian",["PBKS","SRH","RCB","DD","MI"],"All-rounder","Left","Left-arm spin",2008,"2008-2019",0,[false,false],[false,true,false,true,true,true,true]),
P("Shikhar Dhawan","Indian",["DD","SRH","PBKS"],"Batsman","Left","Off-break",2008,"2008-2022",1,[false,false],[true,false,false,false,true,false,false]),
P("Gautam Gambhir","Indian",["DD","KKR"],"Batsman","Left","Off-break",2008,"2008-2018",2,[false,false],[true,false,false,false,false,true,false]),
P("Sachin Tendulkar","Indian",["MI"],"Batsman","Right","Leg-break spin",2008,"2008-2013",1,[false,false],[false,false,false,false,false,true,true]),
P("Rahul Dravid","Indian",["RR","DD"],"Batsman","Right","Off-break",2008,"2008-2013",1,[false,false],[true,false,false,false,false,true,true]),
P("Sourav Ganguly","Indian",["KKR"],"Batsman","Left","Medium",2008,"2008-2011",0,[false,false],[true,false,false,false,false,true,false]),
P("VVS Laxman","Indian",["DC","KKR"],"Batsman","Right","Off-break",2008,"2008-2012",0,[false,false],[false,false,false,false,false,true,false]),
P("Anil Kumble","Indian",["RCB"],"Bowler","Right","Leg-break spin",2008,"2008-2010",0,[false,false],[true,false,false,false,false,true,false]),
P("Zaheer Khan","Indian",["MI","DD","RCB"],"Bowler","Left","Fast-medium",2008,"2008-2015",2,[false,false],[false,false,false,false,false,true,false]),
P("Ishant Sharma","Indian",["KKR","PBKS","SRH","RCB","DD"],"Bowler","Right","Fast",2008,"2008-2021",0,[false,false],[false,false,false,false,false,false,false]),
P("Ravichandran Ashwin","Indian",["CSK","PBKS","DD","RR"],"All-rounder","Right","Off-break spin",2008,"2008-present",1,[false,false],[true,false,false,true,false,false,false]),
P("Ravindra Jadeja","Indian",["RR","CSK","GL"],"All-rounder","Left","Left-arm spin",2008,"2008-present",4,[false,false],[true,true,false,true,false,false,false]),
P("Piyush Chawla","Indian",["KKR","PBKS","MI","CSK"],"Bowler","Right","Leg-break spin",2008,"2008-2022",3,[false,false],[false,false,false,false,false,false,false]),
P("Irfan Pathan","Indian",["KKR","PBKS","SRH"],"All-rounder","Left","Fast-medium",2008,"2008-2017",1,[false,false],[false,false,false,true,false,false,false]),
P("Yusuf Pathan","Indian",["RR","KKR","MI","SRH"],"All-rounder","Right","Off-break spin",2008,"2008-2019",2,[false,false],[false,true,false,true,true,false,false]),
P("Dinesh Karthik","Indian",["DD","RR","PBKS","MI","KKR","RCB"],"Wicketkeeper-Batsman","Right","Medium",2008,"2008-2024",0,[false,false],[true,true,true,false,false,false,false]),
P("Robin Uthappa","Indian",["RCB","KKR","RR","CSK","SRH","PBKS"],"Wicketkeeper-Batsman","Right","Medium",2008,"2008-2022",2,[true,false],[false,false,true,false,true,false,false]),
P("Ajinkya Rahane","Indian",["MI","RR","DC","PBKS","KKR","CSK"],"Batsman","Right","Off-break",2008,"2008-2022",1,[false,false],[false,false,false,false,false,false,false]),
P("Manish Pandey","Indian",["RCB","KKR","SRH","PBKS","LSG"],"Batsman","Right","Medium",2008,"2008-2022",1,[false,false],[false,false,false,false,false,false,false]),
P("Ambati Rayudu","Indian",["MI","CSK"],"Batsman","Right","Off-break",2008,"2008-2023",5,[false,false],[false,true,false,false,false,false,false]),
P("Wriddhiman Saha","Indian",["KKR","CSK","PBKS","SRH","GT"],"Wicketkeeper-Batsman","Right","Medium",2008,"2008-2023",2,[false,false],[false,false,true,false,false,false,false]),
P("Pragyan Ojha","Indian",["DC","SRH","MI","KKR"],"Bowler","Left","Left-arm spin",2008,"2008-2015",2,[false,true],[false,false,false,false,false,false,false]),
P("Amit Mishra","Indian",["DD","DC","SRH"],"Bowler","Right","Leg-break spin",2008,"2008-2021",0,[false,false],[false,false,false,false,false,false,false]),
P("Murali Vijay","Indian",["CSK","DD","PBKS","SRH","KKR"],"Batsman","Right","Off-break",2008,"2008-2020",1,[false,false],[false,false,false,false,false,false,false]),
P("Sreesanth","Indian",["PBKS","RR","KKR"],"Bowler","Right","Fast",2008,"2008-2013",1,[false,false],[false,false,false,false,false,false,false]),
P("Hardik Pandya","Indian",["MI","GT","MI"],"All-rounder","Right","Fast-medium",2015,"2015-present",2,[false,false],[true,true,false,true,true,false,false]),
P("Jasprit Bumrah","Indian",["MI"],"Bowler","Right","Fast",2013,"2013-present",5,[false,true],[false,false,false,false,false,false,false]),
P("Rishabh Pant","Indian",["DD","DC"],"Wicketkeeper-Batsman","Left","Medium",2016,"2016-present",0,[false,false],[true,true,true,false,true,false,false]),
P("KL Rahul","Indian",["RCB","SRH","PBKS","LSG"],"Wicketkeeper-Batsman","Right","Medium",2014,"2014-present",0,[true,false],[true,false,true,false,false,false,false]),
P("Suryakumar Yadav","Indian",["MI"],"Batsman","Right","Medium",2012,"2012-present",5,[false,false],[false,true,false,false,true,false,false]),
P("Shubman Gill","Indian",["KKR","GT","GT"],"Batsman","Right","Medium",2018,"2018-present",1,[true,false],[true,false,false,false,false,false,false]),
P("Ishan Kishan","Indian",["MI","SRH"],"Wicketkeeper-Batsman","Left","Medium",2016,"2016-present",5,[false,false],[false,false,true,false,true,false,false]),
P("Shreyas Iyer","Indian",["DD","DC","KKR","PBKS"],"Batsman","Right","Off-break",2015,"2015-present",1,[false,false],[true,false,false,false,false,false,false]),
P("Deepak Chahar","Indian",["CSK","RR"],"All-rounder","Right","Fast-medium",2018,"2018-present",1,[false,false],[false,false,false,true,false,false,false]),
P("Bhuvneshwar Kumar","Indian",["PBKS","SRH"],"Bowler","Right","Fast-medium",2009,"2009-present",1,[false,true],[false,false,false,false,false,false,false]),
P("Mohammed Shami","Indian",["DD","DC","PBKS","GT"],"Bowler","Right","Fast",2013,"2013-present",1,[false,false],[false,false,false,false,false,false,false]),
P("Yuzvendra Chahal","Indian",["RCB","RR"],"Bowler","Right","Leg-break spin",2014,"2014-present",0,[false,true],[false,false,false,false,false,false,false]),
P("Kuldeep Yadav","Indian",["KKR","DC"],"Bowler","Left","Left-arm wrist spin",2016,"2016-present",0,[false,false],[false,false,false,false,false,false,false]),
P("Washington Sundar","Indian",["RCB","SRH","GT"],"All-rounder","Right","Off-break spin",2017,"2017-present",1,[false,false],[false,false,false,true,false,false,false]),
P("Axar Patel","Indian",["PBKS","DC","GT"],"All-rounder","Left","Left-arm spin",2014,"2014-present",0,[false,false],[false,false,false,true,false,false,false]),
P("Krunal Pandya","Indian",["MI","LSG","RR"],"All-rounder","Left","Left-arm spin",2016,"2016-present",5,[false,false],[false,false,false,true,false,false,false]),
P("Mayank Agarwal","Indian",["RCB","PBKS","SRH"],"Batsman","Right","Off-break",2011,"2011-present",0,[true,false],[true,false,false,false,true,false,false]),
P("Prithvi Shaw","Indian",["DD","DC"],"Batsman","Right","Off-break",2018,"2018-2023",0,[false,false],[false,false,false,false,true,false,false]),
P("Sanju Samson","Indian",["RR","DD"],"Wicketkeeper-Batsman","Right","Medium",2013,"2013-present",1,[false,false],[true,false,true,false,true,false,false]),
P("Nitish Rana","Indian",["MI","KKR","PBKS"],"Batsman","Left","Off-break",2017,"2017-present",1,[false,false],[false,false,false,false,false,false,false]),
P("Tilak Varma","Indian",["MI"],"Batsman","Left","Off-break",2022,"2022-present",5,[false,false],[false,false,false,false,false,false,false]),
P("Ruturaj Gaikwad","Indian",["CSK"],"Batsman","Right","Off-break",2019,"2019-present",2,[true,false],[true,false,false,false,false,false,false]),
P("Venkatesh Iyer","Indian",["KKR"],"All-rounder","Left","Medium",2021,"2021-present",1,[false,false],[false,false,false,true,false,false,false]),
P("Avesh Khan","Indian",["DC","LSG","RR"],"Bowler","Right","Fast",2020,"2020-present",0,[false,false],[false,false,false,false,false,false,false]),
P("Umran Malik","Indian",["SRH","GT"],"Bowler","Right","Fast",2021,"2021-present",0,[false,false],[false,false,false,false,false,false,false]),
P("Arshdeep Singh","Indian",["PBKS"],"Bowler","Left","Fast-medium",2019,"2019-present",0,[false,false],[false,false,false,false,false,false,false]),
P("Rinku Singh","Indian",["KKR"],"Batsman","Left","Medium",2018,"2018-present",1,[false,false],[false,true,false,false,true,false,false]),
P("Yashasvi Jaiswal","Indian",["RR"],"Batsman","Left","Medium",2022,"2022-present",1,[true,false],[false,false,false,false,true,false,false]),
P("Dhruv Jurel","Indian",["RR"],"Wicketkeeper-Batsman","Right","Medium",2022,"2022-present",0,[false,false],[false,false,true,false,false,false,false]),
P("Naman Ojha","Indian",["SRH","MI","DD","PBKS"],"Wicketkeeper-Batsman","Right","Medium",2008,"2008-2018",1,[false,false],[false,false,true,false,false,false,false]),
P("Manoj Tiwary","Indian",["DD","KKR","RCB","PBKS"],"Batsman","Right","Medium",2008,"2008-2019",1,[false,false],[false,false,false,false,false,false,false]),
P("S Badrinath","Indian",["CSK","SRH","PBKS"],"Batsman","Right","Off-break",2008,"2008-2014",1,[false,false],[false,false,false,false,false,false,false]),
P("R Ashwin","Indian",["CSK","PBKS","DD","RR"],"All-rounder","Right","Off-break spin",2008,"2008-present",1,[false,false],[true,false,false,true,false,false,false]),
P("Cheteshwar Pujara","Indian",["RR","CSK","KKR","SRH"],"Batsman","Right","Off-break",2010,"2010-2014",0,[false,false],[false,false,false,false,false,false,false]),
P("Rohit Sharma","Indian",["DC","MI"],"Batsman","Right","Off-break",2008,"2008-present",5,[false,false],[true,false,false,false,true,true,true]),
P("Lendl Simmons","West Indian",["MI","PBKS"],"Batsman","Right","Medium",2008,"2008-2016",2,[false,false],[false,false,false,false,true,false,false]),
// ── OVERSEAS: WEST INDIES ──────────────────────────────────────────────────────
P("Chris Gayle","West Indian",["KKR","RCB","PBKS"],"Batsman","Left","Off-break spin",2008,"2008-2021",0,[true,false],[false,false,false,false,true,true,true]),
P("Kieron Pollard","West Indian",["MI","CSK"],"All-rounder","Right","Fast-medium",2010,"2010-2022",5,[false,false],[false,true,false,true,true,true,false]),
P("Andre Russell","West Indian",["DD","KKR"],"All-rounder","Right","Fast",2012,"2012-present",1,[false,false],[false,true,false,true,true,false,false]),
P("Dwayne Bravo","West Indian",["CSK","GT"],"All-rounder","Right","Fast-medium",2011,"2011-2022",3,[false,true],[false,true,false,true,false,false,false]),
P("Sunil Narine","West Indian",["KKR"],"All-rounder","Left","Off-break spin",2012,"2012-present",3,[false,true],[false,false,false,true,true,false,false]),
P("Marlon Samuels","West Indian",["DD","PBKS"],"All-rounder","Right","Off-break spin",2008,"2008-2014",0,[false,false],[false,false,false,true,false,false,false]),
P("Darren Bravo","West Indian",["MI","CSK"],"Batsman","Left","Medium",2012,"2012-2019",3,[false,false],[false,false,false,false,false,false,false]),
P("Shivnarine Chanderpaul","West Indian",["DD"],"Batsman","Left","Leg-break spin",2008,"2008-2010",0,[false,false],[false,false,false,false,false,false,false]),
P("Jerome Taylor","West Indian",["KKR","MI"],"Bowler","Right","Fast",2008,"2008-2015",2,[false,false],[false,false,false,false,false,false,false]),
P("Fidel Edwards","West Indian",["DC","MI"],"Bowler","Right","Fast",2008,"2008-2012",0,[false,false],[false,false,false,false,false,false,false]),
P("Evin Lewis","West Indian",["MI","RR"],"Batsman","Left","Off-break",2018,"2018-2022",5,[false,false],[false,false,false,false,true,false,false]),
P("Nicholas Pooran","West Indian",["SRH","PBKS","LSG"],"Wicketkeeper-Batsman","Left","Medium",2019,"2019-present",0,[false,false],[false,true,true,false,true,false,false]),
P("Shimron Hetmyer","West Indian",["DC","RCB","RR"],"Batsman","Left","Medium",2019,"2019-present",1,[false,false],[false,true,false,false,true,false,false]),
// ── OVERSEAS: AUSTRALIA ────────────────────────────────────────────────────────
P("Shane Watson","Australian",["RR","RCB","CSK"],"All-rounder","Right","Fast-medium",2008,"2008-2019",2,[false,false],[false,false,false,true,true,true,false]),
P("David Warner","Australian",["DC","SRH"],"Batsman","Left","Leg-break spin",2009,"2009-present",1,[true,false],[true,false,false,false,true,true,true]),
P("Adam Gilchrist","Australian",["DC","PBKS"],"Wicketkeeper-Batsman","Left","Medium",2008,"2008-2012",0,[false,false],[true,false,true,false,true,true,true]),
P("Brett Lee","Australian",["KKR","PBKS","MI"],"Bowler","Right","Fast",2008,"2008-2013",2,[false,false],[false,false,false,false,false,true,false]),
P("Mike Hussey","Australian",["CSK","DC","MI"],"Batsman","Left","Medium",2008,"2008-2013",2,[false,false],[false,true,false,false,false,false,false]),
P("Matthew Hayden","Australian",["CSK"],"Batsman","Left","Medium",2008,"2008-2009",1,[true,false],[false,false,false,false,true,false,false]),
P("Andrew Symonds","Australian",["DC"],"All-rounder","Right","Medium",2008,"2008-2011",0,[false,false],[false,false,false,true,false,false,false]),
P("Shane Warne","Australian",["RR"],"Bowler","Right","Leg-break spin",2008,"2008-2011",1,[false,false],[true,false,false,false,false,true,true]),
P("Mitchell Johnson","Australian",["PBKS","MI"],"Bowler","Left","Fast",2009,"2009-2015",0,[false,false],[false,false,false,false,false,false,false]),
P("Shaun Marsh","Australian",["PBKS"],"Batsman","Left","Medium",2008,"2008-2013",0,[true,false],[false,false,false,false,false,false,false]),
P("Cameron White","Australian",["RCB","DC","SRH"],"Batsman","Right","Leg-break spin",2008,"2008-2013",0,[false,false],[false,false,false,false,false,false,false]),
P("Brad Hodge","Australian",["KKR","RR","DD"],"Batsman","Right","Off-break",2008,"2008-2012",0,[false,false],[false,true,false,false,false,false,false]),
P("Steven Smith","Australian",["RR","PBKS","DC"],"Batsman","Right","Leg-break spin",2012,"2012-2023",1,[false,false],[true,false,false,false,false,false,false]),
P("David Hussey","Australian",["CSK","KKR","MI","PBKS"],"Batsman","Right","Off-break",2008,"2008-2014",2,[false,false],[false,true,false,false,false,false,false]),
P("Mitchell Starc","Australian",["KKR"],"Bowler","Left","Fast",2014,"2014-present",1,[false,false],[false,false,false,false,false,false,false]),
P("Pat Cummins","Australian",["KKR","SRH"],"All-rounder","Right","Fast",2015,"2015-present",1,[false,false],[true,false,false,true,false,false,false]),
P("Tim David","Singaporean",["MI"],"Batsman","Right","Medium",2022,"2022-present",5,[false,false],[false,true,false,false,true,false,false]),
// ── OVERSEAS: SOUTH AFRICA ─────────────────────────────────────────────────────
P("AB de Villiers","South African",["DD","RCB"],"Wicketkeeper-Batsman","Right","Fast-medium",2008,"2008-2021",0,[false,false],[false,true,true,false,true,true,true]),
P("Jacques Kallis","South African",["RCB","KKR"],"All-rounder","Right","Fast-medium",2008,"2008-2014",1,[false,false],[false,false,false,true,false,true,false]),
P("Herschelle Gibbs","South African",["DC","KKR"],"Batsman","Right","Off-break",2008,"2008-2011",0,[false,false],[false,false,false,false,true,false,false]),
P("Morne Morkel","South African",["DD","DC","RR","KKR"],"Bowler","Right","Fast",2008,"2008-2018",0,[false,false],[false,false,false,false,false,false,false]),
P("Dale Steyn","South African",["DC","RCB","GL","PBKS"],"Bowler","Right","Fast",2008,"2008-2020",0,[false,true],[false,false,false,false,false,true,false]),
P("Albie Morkel","South African",["CSK","DD","MI"],"All-rounder","Right","Fast-medium",2008,"2008-2014",1,[false,false],[false,true,false,true,false,false,false]),
P("Faf du Plessis","South African",["CSK","RPS","RCB"],"Batsman","Right","Fast-medium",2012,"2012-present",3,[true,false],[true,false,false,false,false,false,false]),
P("Imran Tahir","South African",["CSK"],"Bowler","Right","Leg-break spin",2015,"2015-2021",1,[false,true],[false,false,false,false,false,false,false]),
P("Quinton de Kock","South African",["MI","RCB","LSG"],"Wicketkeeper-Batsman","Left","Medium",2016,"2016-present",5,[false,false],[false,false,true,false,true,false,false]),
P("David Miller","South African",["PBKS","RR","GT"],"Batsman","Left","Medium",2013,"2013-present",1,[false,true],[false,true,false,false,true,false,false]),
P("Kagiso Rabada","South African",["DD","DC","PBKS","GT"],"Bowler","Right","Fast",2017,"2017-present",1,[false,true],[false,false,false,false,false,false,false]),
P("Marco Jansen","South African",["SRH"],"All-rounder","Left","Fast",2022,"2022-present",0,[false,false],[false,false,false,true,false,false,false]),
// ── OVERSEAS: SRI LANKA ────────────────────────────────────────────────────────
P("Lasith Malinga","Sri Lankan",["MI"],"Bowler","Right","Fast",2009,"2009-2019",4,[false,true],[false,false,false,false,false,true,true]),
P("Kumar Sangakkara","Sri Lankan",["DC","RR","SRH"],"Wicketkeeper-Batsman","Left","Medium",2008,"2008-2015",0,[false,false],[false,false,true,false,false,true,true]),
P("Tillakaratne Dilshan","Sri Lankan",["DD","RR"],"All-rounder","Right","Off-break spin",2008,"2008-2013",1,[false,false],[false,false,false,true,true,false,false]),
P("Mahela Jayawardena","Sri Lankan",["PBKS","MI"],"Batsman","Right","Off-break",2008,"2008-2014",1,[false,false],[false,false,false,false,false,true,false]),
P("Muttiah Muralitharan","Sri Lankan",["CSK","RCB","KKR"],"Bowler","Right","Off-break spin",2008,"2008-2011",1,[false,true],[false,false,false,false,false,true,true]),
P("Angelo Mathews","Sri Lankan",["PBKS","DD","DC","SRH"],"All-rounder","Right","Fast-medium",2009,"2009-2020",0,[false,false],[false,false,false,true,false,false,false]),
P("Nuwan Kulasekara","Sri Lankan",["MI","KKR"],"Bowler","Right","Fast-medium",2008,"2008-2014",2,[false,false],[false,false,false,false,false,false,false]),
P("Dushmantha Chameera","Sri Lankan",["RCB","LSG"],"Bowler","Right","Fast",2016,"2016-present",0,[false,false],[false,false,false,false,false,false,false]),
// ── OVERSEAS: NEW ZEALAND ──────────────────────────────────────────────────────
P("Brendon McCullum","New Zealander",["KKR","CSK","RCB"],"Wicketkeeper-Batsman","Right","Medium",2008,"2008-2014",1,[false,false],[true,false,true,false,true,true,false]),
P("Daniel Vettori","New Zealander",["RCB","DD"],"All-rounder","Left","Left-arm spin",2008,"2008-2014",0,[false,false],[true,false,false,true,false,false,false]),
P("Scott Styris","New Zealander",["DC","CSK","MI"],"All-rounder","Right","Medium",2008,"2008-2012",1,[false,false],[false,false,false,true,false,false,false]),
P("Jacob Oram","New Zealander",["CSK","PBKS","MI"],"All-rounder","Left","Fast-medium",2008,"2008-2012",1,[false,false],[false,false,false,true,false,false,false]),
P("Ross Taylor","New Zealander",["RR","PBKS"],"Batsman","Right","Off-break",2008,"2008-2014",0,[false,false],[false,true,false,false,false,false,false]),
P("Tim Southee","New Zealander",["RCB","MI"],"Bowler","Right","Fast-medium",2009,"2009-2015",0,[false,false],[false,false,false,false,false,false,false]),
P("Mitchell McClenaghan","New Zealander",["MI","PBKS"],"Bowler","Left","Fast",2014,"2014-2019",5,[false,false],[false,false,false,false,false,false,false]),
P("Trent Boult","New Zealander",["MI","RR"],"Bowler","Left","Fast",2015,"2015-present",5,[false,false],[false,false,false,false,false,false,false]),
P("Lockie Ferguson","New Zealander",["KKR","GT","RCB"],"Bowler","Right","Fast",2019,"2019-present",1,[false,false],[false,false,false,false,false,false,false]),
P("Daryl Mitchell","New Zealander",["CSK"],"All-rounder","Right","Medium",2023,"2023-present",1,[false,false],[false,false,false,true,false,false,false]),
// ── OVERSEAS: ENGLAND ──────────────────────────────────────────────────────────
P("Kevin Pietersen","English",["RCB","DD"],"Batsman","Right","Off-break spin",2009,"2009-2014",0,[false,false],[false,false,false,false,true,false,false]),
P("Paul Collingwood","English",["DD"],"All-rounder","Right","Medium",2008,"2008-2009",0,[false,false],[false,false,false,true,false,false,false]),
P("Graeme Swann","English",["DD"],"Bowler","Right","Off-break spin",2008,"2008-2009",0,[false,false],[false,false,false,false,false,false,false]),
P("Andrew Flintoff","English",["CSK"],"All-rounder","Right","Fast-medium",2009,"2009-2010",0,[false,false],[false,false,false,true,false,false,false]),
P("Jos Buttler","English",["MI","RR"],"Wicketkeeper-Batsman","Right","Medium",2016,"2016-present",1,[true,false],[false,false,true,false,true,false,false]),
P("Ben Stokes","English",["RR","CSK"],"All-rounder","Left","Fast-medium",2017,"2017-2023",1,[false,false],[false,false,false,true,true,false,false]),
P("Jonny Bairstow","English",["SRH","PBKS"],"Wicketkeeper-Batsman","Right","Medium",2019,"2019-2022",1,[true,false],[false,false,true,false,true,false,false]),
P("Sam Curran","English",["PBKS","CSK"],"All-rounder","Left","Fast-medium",2019,"2019-present",1,[false,false],[false,true,false,true,false,false,false]),
P("Chris Woakes","English",["DD","RCB","PBKS","KKR"],"All-rounder","Right","Fast-medium",2011,"2011-2022",1,[false,false],[false,false,false,true,false,false,false]),
P("Jason Roy","English",["DD","DC","GT"],"Batsman","Right","Medium",2016,"2016-2023",0,[false,false],[false,false,false,false,true,false,false]),
P("Liam Plunkett","English",["DC"],"Bowler","Right","Fast-medium",2014,"2014-2015",0,[false,false],[false,false,false,false,false,false,false]),
P("Phil Salt","English",["DC","KKR","RCB"],"Wicketkeeper-Batsman","Right","Medium",2022,"2022-present",1,[false,false],[false,false,true,false,true,false,false]),
// ── OVERSEAS: PAKISTAN (pre-2009 ban) ──────────────────────────────────────────
P("Shoaib Akhtar","Pakistani",["KKR"],"Bowler","Right","Fast",2008,"2008-2008",0,[false,false],[false,false,false,false,false,false,false]),
P("Shoaib Malik","Pakistani",["DD"],"All-rounder","Right","Off-break spin",2008,"2008-2009",0,[false,false],[false,false,false,true,false,false,false]),
P("Mohammad Asif","Pakistani",["DC"],"Bowler","Right","Fast-medium",2008,"2008-2009",0,[false,false],[false,false,false,false,false,false,false]),
// ── OVERSEAS: AFGHANISTAN ──────────────────────────────────────────────────────
P("Rashid Khan","Afghan",["SRH","GT"],"All-rounder","Right","Leg-break spin",2017,"2017-present",1,[false,true],[false,false,false,true,false,false,false]),
P("Mohammad Nabi","Afghan",["SRH"],"All-rounder","Right","Off-break spin",2019,"2019-2022",1,[false,false],[false,false,false,true,false,false,false]),
P("Mujeeb ur Rahman","Afghan",["PBKS","MI"],"Bowler","Right","Off-break spin",2018,"2018-present",5,[false,false],[false,false,false,false,false,false,false]),
// ── OVERSEAS: ZIMBABWE/OTHERS ──────────────────────────────────────────────────
P("Brendan Taylor","Zimbabwean",["KKR"],"Wicketkeeper-Batsman","Right","Off-break",2010,"2010-2011",1,[false,false],[false,false,true,false,false,false,false]),
P("Elton Chigumbura","Zimbabwean",["RR","DC"],"All-rounder","Right","Fast-medium",2010,"2010-2013",0,[false,false],[false,false,false,true,false,false,false]),
P("Heinrich Klaasen","South African",["SRH"],"Wicketkeeper-Batsman","Right","Medium",2018,"2018-present",0,[false,false],[false,true,true,false,true,false,false]),
P("Tristan Stubbs","South African",["MI"],"Wicketkeeper-Batsman","Right","Medium",2023,"2023-present",5,[false,false],[false,true,true,false,true,false,false]),
];

// Remove exact duplicates by name
const PLAYERS = [...new Map(IPL_PLAYERS.map(p => [p.name, p])).values()];

// ─── QUESTION BANK (25 questions) ─────────────────────────────────────────────
const QUESTIONS = [
  { id:"overseas",    text:"Is your player an overseas (non-Indian) cricketer?",             eval: p => p.overseas },
  { id:"keeper",      text:"Is your player a wicketkeeper?",                                  eval: p => p.keeper },
  { id:"allrounder",  text:"Is your player an all-rounder (bats AND bowls significantly)?",  eval: p => p.allrounder },
  { id:"pace",        text:"Is your player primarily a pace/fast bowler?",                    eval: p => p.pace && !p.allrounder },
  { id:"spin",        text:"Is your player primarily a spin bowler?",                         eval: p => p.spin && !p.allrounder },
  { id:"leftBat",     text:"Is your player a left-handed batsman?",                           eval: p => p.leftBat },
  { id:"captain",     text:"Has your player captained an IPL team?",                          eval: p => p.captain },
  { id:"finisher",    text:"Is your player known as a finisher or death-overs specialist?",  eval: p => p.finisher },
  { id:"aggressive",  text:"Is your player known as an explosive power-hitter or aggressive opener?", eval: p => p.aggressive },
  { id:"legend",      text:"Is your player widely considered a legend of the game?",          eval: p => p.legend },
  { id:"titles",      text:"Has your player won at least one IPL title?",                     eval: p => p.titles > 0 },
  { id:"multiTitles", text:"Has your player won 3 or more IPL titles?",                      eval: p => p.titles >= 3 },
  { id:"iconic",      text:"Is your player one of the most iconic IPL players ever?",        eval: p => p.iconic },
  { id:"orangeCap",   text:"Has your player won the Orange Cap (top run-scorer in a season)?",eval: p => p.orangeCap },
  { id:"purpleCap",   text:"Has your player won the Purple Cap (top wicket-taker in a season)?",eval: p => p.purpleCap },
  { id:"active",      text:"Is your player still active in IPL (playing in recent seasons 2020+)?", eval: p => p.active },
  { id:"earlyEra",    text:"Did your player play prominently in the early IPL era (2008-2012)?", eval: p => p.earlyEra },
  { id:"csk",         text:"Has your player been associated with Chennai Super Kings (CSK)?", eval: p => p.teams.includes("CSK") },
  { id:"mi",          text:"Has your player been associated with Mumbai Indians (MI)?",       eval: p => p.teams.includes("MI") },
  { id:"rcb",         text:"Has your player been associated with Royal Challengers Bangalore (RCB)?", eval: p => p.teams.includes("RCB") },
  { id:"kkr",         text:"Has your player been associated with Kolkata Knight Riders (KKR)?", eval: p => p.teams.includes("KKR") },
  { id:"rr",          text:"Has your player been associated with Rajasthan Royals (RR)?",    eval: p => p.teams.includes("RR") },
  { id:"srh",         text:"Has your player been associated with SRH or Deccan Chargers (DC)?", eval: p => p.teams.includes("SRH") || p.teams.includes("DC") },
  { id:"pbks",        text:"Has your player been associated with Punjab Kings / KXIP?",       eval: p => p.teams.includes("PBKS") },
  { id:"singleTeam",  text:"Has your player played for only ONE IPL team throughout their career?", eval: p => p.teams.length === 1 },
];
